# Generated by Django 3.2 on 2022-09-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_rating_ratingstar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actors')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='film.actor')),
            ],
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.movie', verbose_name='film'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.ratingstar', verbose_name='star'),
        ),
        migrations.DeleteModel(
            name='MovieShots',
        ),
    ]
